---
 - name: Discovery Play
   hosts: all
   #gather_facts: no
   tasks:
   - name: Find os name
     shell: "uname"
     register: os_name
   - name: Find uptime
     shell: "uptime"
     register: up_time
   - name: Display Discovery info
     debug: 
      msg: "{{inventory_hostname}},{{ansible_os_family}},{{ansible_system}},{{ansible_distribution}},{{up_time.stdout.split(',')[0].split('up')[-1]}}"
   - name: Remove old discovery.csv file
     file:
      dest: ./Discovery.csv
      state: absent
     delegate_to: localhost
     run_once: yes
   - name: Create Discovery.csv file with header
     copy:
      dest: ./Discovery.csv
      content: "Server_name, OS Family, OS Name, OS Distribution, uptime\n"
     delegate_to: localhost
     run_once: yes
   - name: Update info in Discovery.csv file
     lineinfile:
      path: ./Discovery.csv
      line: "{{inventory_hostname}},{{ansible_os_family}},{{ansible_system}},{{ansible_distribution}},{{up_time.stdout.split(',')[0].split('up')[-1]}}"
     delegate_to: localhost
